
declare @table table (COD_TELEATENDIMENTO bigint, COD_TIPO_TELEATENDIMENTO int, NR_ATENDIMENTO int, COD_NATUREZA int, DT_CADASTRO datetime, DSC_NATUREZA varchar(200), COD_NATUREZA_GRUPO int, DSC_NATUREZA_GRUPO varchar(200))
INSERT INTO @table
SELECT         dbo.TP_TELEATENDIMENTO.COD_TELEATENDIMENTO, dbo.TP_TELEATENDIMENTO.COD_TIPO_TELEATENDIMENTO, dbo.TP_TELEATENDIMENTO.NR_ATENDIMENTO, dbo.TP_TELEATENDIMENTO.COD_NATUREZA, 
                         dbo.TP_TELEATENDIMENTO.DT_CADASTRO, dbo.TA_NATUREZA.DSC_NATUREZA, NULL, null 
FROM            dbo.TA_NATUREZA INNER JOIN
                         dbo.TP_TELEATENDIMENTO ON dbo.TA_NATUREZA.COD_NATUREZA = dbo.TP_TELEATENDIMENTO.COD_NATUREZA
WHERE        (dbo.TP_TELEATENDIMENTO.COD_TIPO_TELEATENDIMENTO = 5)
ORDER BY dbo.TP_TELEATENDIMENTO.COD_TELEATENDIMENTO DESC
--select * from @table




UPDATE t1
SET t1.COD_NATUREZA_GRUPO =  t2.COD_NATUREZA_GRUPO
FROM @table AS t1
INNER JOIN TA_NATUREZA AS t2
ON t1.COD_NATUREZA = t2.COD_NATUREZA