UPDATE t1
SET t1.NR_ATENDIMENTO =  convert(bigint, t2.COD_OCORRENCIA_SGO)
FROM TP_TELEATENDIMENTO AS t1
INNER JOIN @table2 AS t2
ON t1.COD_TELEATENDIMENTO = t2.COD_TELEATENDIMENTO
where t1.NR_ATENDIMENTO is null 
 
 